// AUTO-GENERATED by functions/scripts/sync-templates.js — do not edit by hand.
// Source: src/lib/pdf/<filename>.ts. Run `npm --prefix functions run sync`
// after editing the canonical template.

import { renderInvoiceHtml as renderProHtml, type RenderInvoiceArgs } from "./invoice-pro";

export type { RenderInvoiceArgs };

// Wraps the Pro template and injects a "Made with Folio" watermark footer.
// position: fixed renders on every page in Chromium (Puppeteer) and WKWebView.
// The watermark is baked into the HTML — it cannot be toggled via CSS from
// the client side.
export function renderInvoiceHtml(args: RenderInvoiceArgs): string {
  const html = renderProHtml(args);
  const withCss = html.replace(
    "</style>",
    `    .folio-watermark {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      text-align: center;
      font-family: "Inter", sans-serif;
      font-size: 9pt;
      color: rgba(156, 163, 175, 0.5);
      padding: 4px 0;
    }\n  </style>`,
  );
  return withCss.replace(
    "</body>",
    `  <div class="folio-watermark">Made with Folio • folio.app</div>\n</body>`,
  );
}
